version: "3.9"  # optional since v1.27.0

services:
  keycloak:
    image: sleighzy/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: fausto123
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      # - ./keycloak/themes/custom_theme_name:/opt/jboss/keycloak/themes/custom_theme_name
      - ./scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - travel-app-network
  mysql:
    image: mysql:8.0.30
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/initdbs.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - travel-app-network
    ports:
      - "3399:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    env_file:
      # - .production.env
      - .development.env
    container_name: travel-app-backend
    restart: always
    build: .
    ports:
      - 4001:3001
    depends_on:
      - mysql  
    links:
      - mysql
      - keycloak
    networks:
      - travel-app-network   
networks:
  travel-app-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local